CREATE TABLE IF NOT EXISTS `form_quest` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `date` datetime NOT NULL,
  `pid` bigint(20) NOT NULL,
  `user` varchar(255) NOT NULL,
  `groupname` varchar(255) DEFAULT NULL,
  `authorized` tinyint(4) DEFAULT NULL,
  `activity` tinyint(4) DEFAULT NULL,
  `status` varchar(16) DEFAULT NULL,
  `priority` varchar(16) DEFAULT NULL,
  `facility_id` int(11) DEFAULT NULL,
  `lab_id` varchar(25) DEFAULT NULL,
  `pat_fname` varchar(255) DEFAULT NULL,
  `pat_mname` varchar(255) DEFAULT NULL,
  `pat_lname` varchar(255) DEFAULT NULL,
  `pat_DOB` date DEFAULT NULL COMMENT 'used in result matching',
  `pat_race` varchar(31) DEFAULT NULL,
  `pat_ss` varchar(31) DEFAULT NULL,
  `pat_pubpid` varchar(31) DEFAULT NULL,
  `doc_npi` varchar(255) DEFAULT NULL,
  `doc_lname` varchar(255) DEFAULT NULL,
  `doc_fname` varchar(255) DEFAULT NULL,
  `doc_mname` varchar(255) DEFAULT NULL,
  `ins_primary` bigint(20) DEFAULT '0',
  `ins_secondary` bigint(20) DEFAULT '0',
  `diagnoses` text,
  `order_number` varchar(225) NOT NULL,
  `order_type` varchar(255) DEFAULT NULL, ???
  `order_psc` tinyint(4) DEFAULT NULL,  ???
  `order_pending` datetime DEFAULT NULL,  ???
  `order_req_id` varchar(255) DEFAULT NULL,
  `order_abn_id` varchar(255) DEFAULT NULL,
  `order_abn_signed` char(1) DEFAULT NULL,
  `order_notes` text,
  `work_flag` char(1) DEFAULT NULL,
  `work_insurance` varchar(25) DEFAULT NULL,
  `work_date` date DEFAULT NULL,
  `work_employer` varchar(25) DEFAULT NULL,
  `work_case` varchar(25) DEFAULT NULL,
  `request_billing` varchar(32) DEFAULT NULL,
  `request_account` varchar(25) DEFAULT NULL,
  `request_handling` varchar(255) DEFAULT NULL,
  `request_notes` text,
  `result_doc_id` varchar(255) DEFAULT NULL,
  `result_datetime` datetime DEFAULT NULL,
  `result_abnormal` int(5) DEFAULT '0',
  `lab_number` varchar(255) DEFAULT NULL,
  `reviewed_datetime` datetime DEFAULT NULL,
  `reviewed_id` bigint(20) DEFAULT NULL,
  `notified_datetime` datetime DEFAULT NULL,
  `notified_person` varchar(255) DEFAULT NULL,
  `notified_id` bigint(20) DEFAULT NULL,
  `review_notes` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_idx` (`order_number`),
  KEY `pid_idx` (`pid`),
  KEY `status_idx` (`status`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
