CREATE TABLE IF NOT EXISTS `procedure_order` (
  `procedure_order_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `uuid` binary(16) DEFAULT NULL,
  `provider_id` bigint(20) DEFAULT '0' COMMENT 'references users.id, the ordering provider',
  `patient_id` bigint(20) NOT NULL COMMENT 'references patient_data.pid',
  `encounter_id` bigint(20) DEFAULT '0' COMMENT 'references form_encounter.encounter',
  `date_collected` datetime DEFAULT NULL COMMENT 'time specimen collected',
  `date_ordered` datetime DEFAULT NULL,
  `order_priority` varchar(31) DEFAULT '',
  `order_status` varchar(31) DEFAULT '' COMMENT 'pending,routed,complete,canceled',
  `patient_instructions` text,
  `activity` tinyint(1) DEFAULT '1' COMMENT '0 if deleted',
  `control_id` varchar(255) DEFAULT '' COMMENT 'This is the CONTROL ID that is sent back from lab',
  `lab_id` bigint(20) DEFAULT '0' COMMENT 'references procedure_providers.ppid',
  `specimen_draw` varchar(8) DEFAULT NULL,
  `specimen_type` varchar(31) DEFAULT NULL,
  `specimen_location` varchar(31) DEFAULT NULL,
  `specimen_volume` varchar(31) DEFAULT NULL,
  `date_pending` datetime DEFAULT NULL,
  `date_transmitted` datetime DEFAULT NULL COMMENT 'time of order transmission, null if unsent',
  `clinical_hx` varchar(255) DEFAULT NULL,
  `specimen_fasting` varchar(31) DEFAULT NULL,
  `specimen_duration` varchar(31) DEFAULT NULL,
  `specimen_transport` varchar(31) DEFAULT NULL,
  `specimen_source` varchar(31) DEFAULT NULL,
  `external_id` varchar(20) DEFAULT NULL,
  `history_order` enum('0','1') DEFAULT '0',
  `portal_flag` tinyint(1) DEFAULT '0',
  `tav_done` tinyint(1) DEFAULT '0',
  `order_diagnosis` varchar(255) DEFAULT NULL,
  `billing_type` varchar(4) DEFAULT NULL,
  `order_psc` tinyint(4) DEFAULT NULL,
  `order_abn` varchar(31) DEFAULT NULL,
  `collector_id` bigint(11) DEFAULT NULL,
  `account` varchar(60) DEFAULT NULL,
  `account_facility` bigint(11) DEFAULT NULL,
  `provider_number` varchar(30) DEFAULT NULL,
  `procedure_order_type` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`procedure_order_id`),
  KEY `date_pid` (`date_ordered`,`patient_id`),
  KEY `patient_id` (`patient_id`),
  KEY `provider_idx` (`provider_id`),
  KEY `encounter_idx` (`encounter_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
